return (function()
	--require('plug-settings.lua.lsp.init')
	require('plug-settings.compe')
	require('plug-settings.lspinstall')
	require('plug-settings.lspconfig')
	require('plug-settings.lspsignature')
	require('plug-settings.gitsigns')
	require('plug-settings.ultisnips')
	require('plug-settings.telescope')
	require('plug-settings.lualine')
end)()
